package org.scify.engine;

public enum EpisodeEndStateCode {
    EPISODE_FINISHED_SUCCESS,
    EPISODE_FINISHED_FAILURE,
    EPISODE_INTERRUPTED,
    CALCULATOR_STARTED,
    PREVIOUS_EPISODE,
    APP_QUIT,
    MAP_EPISODE_STARTED,
    SPACESHIP_CHARGER_EPISODE_STARTED,
    TEMP_EPISODE_FINISHED,
    SIMPLE_TIMED_IMAGE_EPISODE
}
