package org.scify.engine;

public enum EpisodeEndStateCode {
    EPISODE_FINISHED_SUCCESS,
    EPISODE_FINISHED_FAILURE,
    EPISODE_INTERRUPTED,
    CALCULATOR_STARTED,
    PREVIOUS_EPISODE,
    APP_QUIT,
    TEMP_EPISODE_FINISHED
}
